spring:
  profiles:
    active: @spring.profiles.active@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
  mvc:
    pathmatch:
      # See https://github.com/springfox/springfox/issues/3462#issuecomment-978707909
      matching-strategy: ant_path_matcher

  #navi:
#  security:
#    jwt:
#      validity: ${TOKEN_VALIDITY_IN_MILLISECONDS}
#      secret: ${BASE64_ENCODED_SECRET}
